package myth

import org.junit.Test
import spock.lang.Specification



/**
 * AutoGenerated BY AutoUTGenerator.groovy
 */
class AddAutoTest extends Specification {

   def add = new Add()

   @Test
    def "testAdd(int,int)"() {
        expect:
        add.invokeMethod("add", [intval0,intval1]) == resultintval

        where:
        intval0 | intval1     | resultintval
        0 | 0 | 0

    }

}