package myth

import org.junit.Test
import spock.lang.Specification



/**
 * AutoGenerated BY AutoUTGenerator.groovy
 */
class SumAutoTest extends Specification {

   def sum = new Sum()

   @Test
    def "testSum(int,int)"() {
        expect:
        sum.invokeMethod("sum", [intval0,intval1]) == resultintval

        where:
        intval0 | intval1     | resultintval
        0 | 0 | 0

    }

}